name: Update

run-name: "Update tags"

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0,12 * * *'


jobs:
  update:
    name: Update tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install git+https://github.com/royaurelien/pyhub.git@main

      - name: Fetch tags
        shell: bash
        env:
            NAME: ${{ vars.DOCKER_REPOSITORY }}
            PYHUB_REPO_TAGS_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            PYHUB_REPO_TAGS_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            PYHUB_REPO_TAGS_ORG: ${{ secrets.DOCKER_ORG }}
        run: |
          result=$(pyhub-cli repo tags $NAME \
          -f name -f full_size -f tag_last_pulled -f tag_last_pushed \
          -o json)
          echo "$result" > ./tags.json

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v4
      - name: Add workflows
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run static.yml