name: Update

run-name: "Update tags"

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0,12 * * *'


jobs:
  update:
    name: Update tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: apikcloud/dockerhub-fetch-tags-action@main
        with:
          org: ${{ secrets.DOCKER_ORG }}
          repo: ${{ vars.DOCKER_REPOSITORY }}
          login: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v4
      - name: Add workflows
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run static.yml